language: python

python:
  - "3.8"

cache:
  - pip

before_install:
  - pip install -U pip
  - pip install pip-tools

install:
  - make sync-deps
  - pip install codecov

script:
  - make test-ci

after_success:
  - codecov