language: python

python:
  - "3.8"

before_install:
  - pip install -U pip
  - pip install codecov
  - pip install pip-tools

install:
  - make sync-deps

script:
  - make test-ci

after_success:
  - codecov