site_name: Cloudflare DNS Updater
site_url: https://example.com/
site_author: Daniel Różycki
repo_url: https://github.com/AlTosterino/cloudflare-dns-updater
repo_name: AlTosterino/cloudflare-dns-updater

theme:
  name: material
  custom_dir: overrides

  icon:
    repo: fontawesome/brands/github

  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - toc.follow
    -
  plugins:
    - search
    - git-revision-date-localized:
        type: date

  extra:
    version:
      provider: mike

markdown_extensions:
  - abbr
  - admonition
  - def_list
  - footnotes
  - meta
  - tables

extra:
  version:
    provider: mike

plugins:
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true